/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/layout/AppNavbar.vue')['default']
    CatalogFilterSidebar: typeof import('./components/catalogo/CatalogFilterSidebar.vue')['default']
    CatalogPagination: typeof import('./components/catalogo/CatalogPagination.vue')['default']
    CatalogProductCard: typeof import('./components/catalogo/CatalogProductCard.vue')['default']
    CatalogSortDropdown: typeof import('./components/catalogo/CatalogSortDropdown.vue')['default']
    HeroBannerDesktop: typeof import('./components/home/HeroBannerDesktop.vue')['default']
    HeroBannerMobile: typeof import('./components/home/HeroBannerMobile.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    ProductFinishesSelector: typeof import('./components/produto/ProductFinishesSelector.vue')['default']
    ProductGallery: typeof import('./components/produto/ProductGallery.vue')['default']
    ProductShowroomCard: typeof import('./components/produto/ProductShowroomCard.vue')['default']
    ProductSpecsTable: typeof import('./components/produto/ProductSpecsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./components/ui/UiButton.vue')['default']
    UiCard: typeof import('./components/ui/UiCard.vue')['default']
    UiFloatingActions: typeof import('./components/ui/UiFloatingActions.vue')['default']
    UiFloatingButton: typeof import('./components/ui/UiFloatingButton.vue')['default']
    UiModal: typeof import('./components/ui/UiModal.vue')['default']
  }
}
