/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/layout/AppNavbar.vue')['default']
    HeroBannerDesktop: typeof import('./components/home/HeroBannerDesktop.vue')['default']
    HeroBannerMobile: typeof import('./components/home/HeroBannerMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./components/ui/UiButton.vue')['default']
    UiCard: typeof import('./components/ui/UiCard.vue')['default']
    UiFloatingActions: typeof import('./components/ui/UiFloatingActions.vue')['default']
    UiFloatingButton: typeof import('./components/ui/UiFloatingButton.vue')['default']
    UiModal: typeof import('./components/ui/UiModal.vue')['default']
  }
}
