name: Deploy na VM

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy em Produção
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /
          cd /var/www/html/site-emporio-henz
          sudo git status
          sudo git checkout main
          sudo git  pull origin main
          ./deploy.sh
