name: Deploy na VM

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy em Produção
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /var/www/html/site-emporio-henz
          git status
          git checkout main
          git pull origin main
          chmod +x deploy.sh
          ./deploy.sh
